version: "3.8"

services:
 
###################################################################
# Services
###################################################################
  fastapi:
    image: mbari/fastapi-vss:${GIT_VERSION}
    container_name: fastapi-vss
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8000/health" ]
    env_file:
      - .env
    ports:
      - "8000:80"
    environment:
      - CONFIG_PATH=/config
    volumes:
      - ./config:/config
    user: ${MLDEVOPS_GID}:${MLDEVOPS_UID}
    restart: always
    depends_on:
      - redis
    networks:
      - vss
  redis:
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWD:?REDIS_PASSWD variable is not set}"
    image: redis/redis-stack-server
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - vss
volumes:
  redis-data:
networks:
  vss:
