version: "3.8"

###################################################################
# Services
###################################################################
services:
  fastapi-vss:
    image: mbari/fastapi-vss:0.1.0:${GIT_VERSION}
    container_name: fastapi-vss
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
    env_file:
      - ./.env
    environment:
      - PORT=8001
    volumes:
      - /tmp/fastapi-vssgit/.env:/app/.env
    network_mode: host
    restart: always
