services:

###################################################################
# Services
###################################################################
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: mbari/fastapi-vss:${GIT_VERSION}
    container_name: fastapi-vss
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://fastapi-vss:8000/health | grep '\"status\":\"ok\"'"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - uvicorn src.app.main:app --host 0.0.0.0 --port 80
    ports:
      - "8000:80"
    environment:
      - LOG_DIR=${LOG_PATH}/fastapi
    volumes:
      - ${CONFIG_PATH}:${CONFIG_PATH}
      - ${LOG_PATH}:${LOG_PATH}
      - ./data:/data
    user: ${MLDEVOPS_GID}:${MLDEVOPS_UID}
    restart: always
    depends_on:
      - redis
    networks:
      - vss
  redis:
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-stack-server  --port 6379 --appendonly yes --appendfsync everysec --requirepass "$${REDIS_PASSWD:?REDIS_PASSWD variable is not set}"
    image: redis/redis-stack-server
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - vss
  rq-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: mbari/fastapi-vss:${GIT_VERSION}
    container_name: rq-worker-vss
    environment:
      - REDIS_PASSWD=${REDIS_PASSWD}
      - REDIS_URL=redis://default:${REDIS_PASSWD}@redis:6379
      - LOG_DIR=${LOG_PATH}
    entrypoint:
        - /bin/sh
        - -c
        - python /app/tests/load.py && rq worker --url redis://default:${REDIS_PASSWD}@redis:6379 default
    volumes:
      - ${CONFIG_PATH}:${CONFIG_PATH}
      - ${LOG_PATH}:${LOG_PATH}
      - ./data:/data
      - ./tests:/app/tests
    depends_on:
      - fastapi
    networks:
      - vss
volumes:
  redis-data:
networks:
  vss:
