services:

###################################################################
# Services
###################################################################
  fastapi:
    image: mbari/fastapi-vss:${GIT_VERSION}
    container_name: fastapi-vss
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8000/health" ]
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - uvicorn src.app.main:app --host  0.0.0.0 --port 80 --reload --reload-dir /app/src/
    ports:
      - "8000:80"
    volumes:
      - ${CONFIG_PATH}:${CONFIG_PATH}
      - ./logs_fapi:/app/src/app/logs
      - ./src:/app/src
    user: ${MLDEVOPS_GID}:${MLDEVOPS_UID}
    restart: always
    depends_on:
      - redis
    networks:
      - vss
  redis:
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-stack-server  --port 6379 --appendonly yes --appendfsync everysec --requirepass "$${REDIS_PASSWD:?REDIS_PASSWD variable is not set}"
    image: redis/redis-stack-server
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - vss
  rq-worker:
    env_file:
      - .env
    image: mbari/fastapi-vss:${GIT_VERSION}
    container_name: rq-worker-vss
    environment:
      - REDIS_PASSWD=${REDIS_PASSWD}
      - REDIS_URL=redis://default:${REDIS_PASSWD}@redis:6379
    entrypoint:
        - /bin/sh
        - -c
        - rq worker --url redis://default:${REDIS_PASSWD}@redis:6379 default
    volumes:
      - ./config:/config
      - ./logs_worker:/app/src/app/logs
    depends_on:
      - redis
    networks:
      - vss
volumes:
  redis-data:
networks:
  vss:
