# Config file for 902004-Planktivore project
redis:
  host: "doris.shore.mbari.org"
#  port: 6383
  port: 6379

vss:
  threshold: 0.9
  model: "google/vit-base-patch16-224"
  project: "902004-Planktivore"

tator:
  project: "902004-Planktivore"
  host: "mantis.shore.mbari.org"
