# Config file for 902111-CFE project
redis:
  host: "doris.shore.mbari.org"
  port: 6382

data:
  raw_data_path: "/mnt/CFElab/"
  processed_path: "/mnt/ML_SCRATCH/902111-CFE"
  version: "Baseline"
  labels: "copepod"
  download_args: ["--verified"]

sdcat:
  model: "hustvl/yolos-tiny"
  clu_det_ini: "sdcat_clu_det.ini"
  exemplar_ini: "sdcat_exemplar.ini"

vss:
  project: "cfe"
  threshold: 0.9
  model: "google/vit-base-patch16-224"

tator:
  project: "902111-CFE"
  host: "mantis.shore.mbari.org"
  bulk_url: "http://mantis.shore.mbari.org:8001/label/id"

  image:
    attributes:
      iso_datetime:
        type: string
      depth:
        type: int

  box:
    attributes:
      Label:
        type: string
      concept:
        type: string
      score:
        type: float
      cluster:
        type: string
      saliency:
        type: float
      group:
        type: string
      obs_uuid:
        type: string
      exemplar:
        type: bool
      verified:
        type: bool


ffmpeg_path: "/usr/bin/ffmpeg"
