# Config file for 902111-CFE project
redis:
  host: "doris.shore.mbari.org"
  port: 6382

vss:
  threshold: 0.9
  model: "google/vit-base-patch16-224"
  project: "902111-CFE"

tator:
  project: "902111-CFE"
  host: "mantis.shore.mbari.org"