# Config file for 901103-biodiversity project
redis:
  host: "doris.shore.mbari.org"
  port: 6381

vss:
  threshold: 0.9
  model: "google/vit-base-patch16-224"
  project: "901103-biodiversity"

tator:
  project: "901103-biodiversity"
  host: "mantis.shore.mbari.org"