# config.yml
# Config file for testing and development

redis:
  host: "redis"
  port: 6379
  project: "testproject"

vss:
  model: "google/vit-base-patch16-224" # Model to use for VSS can be a Hugging Face model ID or a local path
  project: "testproject" # Project name for VSS
  output_path: "/data/vss/outputs"  # Directory where VSS saves JSON results
