# config.dev.yml
# Config file for development

redis:
  host: "localhost"  # Used when running natively (outside Docker)
  internal_host: "redis-stack"  # Docker Compose service name (same as in compose.yml)
  port: 6379
  project: "testproject"

vss:
  model: "/Users/dcline/Dropbox/code/ai/fastapi-vss/models/vit-base-patch16-224" # Model to use for VSS can be a Hugging Face model ID or a local path
  project: "testproject" # Project name for VSS
  output_path: "/Users/dcline/Dropbox/code/ai/fastapi-vss/config/dev/outputs"  # Directory where VSS saves JSON results
