# config_sony.yml
# Config file for SONY image metadata extraction
mounts:
  - name: "image"
    path: "/mnt/UAV"
    host: "mantis.shore.mbari.org"
    nginx_root: "/UAV"

redis:
  host: "ada.local"
  port: 6380